### ISSUE TITLE
Icons Request - Wine, GNOME Todo and Characters

### ISSUE THREAD

**Issue by dyskette** [snwh/moka-icon-theme#261]
GNOME
- [ ] GNOME Todo `org.gnome.Todo` [Image](https://cloud.githubusercontent.com/assets/6687927/17465509/89a72254-5cbe-11e6-9112-4f053a0949a5.png)
- [ ] GNOME Characters `gnome-characters` [Image](https://cloud.githubusercontent.com/assets/6687927/17465524/d3a1fd34-5cbe-11e6-98be-0b91d9845f7e.png)

Wine in Fedora 24
- [ ] Wine File `winefile` (Already exists as `wine` in the theme)
- [ ] Wine Software `msiexec` (Already exists as `wine-uninstaller` in the theme)
- [ ] Notepad `notepad` (Already exists as `wine-notepad` in the theme)
- [ ] Wine Help `winhelp` (Already exists as `wine-help` in the theme)
- [ ] Wine Wordpad `wordpad` (Already exists as `wine-wordpad` in the theme)
- [ ] WineMine `winemine` [Image](https://cloud.githubusercontent.com/assets/6687927/17465553/d9c3f4c8-5cbf-11e6-806d-7cd20f2137b9.png)
- [ ] Regedit `regedit` [Image](https://cloud.githubusercontent.com/assets/6687927/17465613/e4dc45fc-5cc1-11e6-954b-ce261f829307.png)
